sudo: required
services:
  - docker

script:
  - docker build -t babafall/node .
  - docker images babafall/node

before_deploy:
  - docker login -u pbfall -p PBf-Odd-1990

  deploy:
    provider: script
    script: docker push pbfall/testnode