sudo: required
services:
  - docker

script:
  - docker build -t babafall/node .
  - docker images babafall/node

before_deploy:
  - docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD

  deploy:
    provider: script
    script: docker push DOCKER_USERNAM/ note_travis_ci
    on:
      branch: master