sudo: required
services:
  - docker

script:
  - docker build -t pbfall/node2 .
  - docker images pbfall/node2

before_deploy:
  - docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD

  deploy:
    provider: script
    script: docker push DOCKER_USERNAME/note_travis_ci
    on:
      branch: master