sudo: required
services:
  - docker

script:
  - docker build -t babafall/node .
  - docker images babafall/node

before_deploy:
  - docker login -u user -p pwd

  deploy:
    provider: script
    script: docker push user/repersitory
    on:
      branch: master