sudo: required
services:
  - docker

script:
  - docker build -t pbfall/nodetestwithtravis .
  - docker images pbfall/nodetestwithtravis

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  deploy:
    provider: script
    script: docker push $DOCKER_USERNAME/nodetestwithtravis
    on:
      branch: master